name: Build and Deploy ASP .NET Core Chapter 12 to GitHub Pages

on:
  push:
    branches: [ master ]    
    paths: 
    - './Chapter 12/Chapter_12_GitHubActions_Examples/**'

jobs:  
  build:    
    steps:
      # steps to build the application
  
  deploy:
    steps:
      # steps to deploy the application
